name: 'Submitty Action Docker Matrix'
description: 'Builds the matrix for reusable docker build action'
inputs:
  docker-username:
    required: true
    type: string
  base-commit:
    required: true
    type: string
  head-commit:
    required: true
    type: string
outputs:
  matrix:
    value: ${{ steps.generate-matrix.outputs.matrix }}
  run_docker_jobs:
    value: ${{ steps.set-run-docker.outputs.run_docker_jobs }}
runs:
  using: "composite"
  steps:
    - name: Generate Matrix
      id: generate-matrix
      shell: bash
      run: echo "matrix=$(python3 ${{ github.action_path }}/bin/generate_matrix.py ${{ inputs.docker-username }} ${{ inputs.base-commit }} ${{ inputs.head-commit }})" >> $GITHUB_OUTPUT
    - name: List Matrix
      shell: bash
      run: |
        echo ${{ steps.generate-matrix.outputs.matrix }}
    - name: Set Run Condition
      id: set-run-docker
      shell: bash
      run: |
          num_to_build=$(echo '${{ steps.generate-matrix.outputs.matrix }}' | jq '.include | length')
          if [[ "$num_to_build" -eq 0 ]]; then
            echo "run_docker_jobs=false" >> $GITHUB_OUTPUT
          else
            echo "run_docker_jobs=true" >> $GITHUB_OUTPUT
          fi
